---
abstract: 'Static analysis of Perl documents'
author:
  - 'Gregor Goldbach <ggoldbach@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PSA
no_index:
  directory:
    - t
    - inc
requires:
  Getopt::Long: 0
  IO::Interactive: 0
  Module::Runtime: 0
  Moose: 0
  PPI: 0
  Term::ANSIColor: 0
version: 0.002
